server:
  port: 8088

---

spring:
  profiles: default
  cloud:
    gateway:
      routes:
        - id: drive
          uri: http://localhost:0
          predicates:
            - Path=/files/**, 
        - id: indexer
          uri: http://localhost:0
          predicates:
            - Path=/fileIndices/**, 
        - id: videoProcessing
          uri: http://localhost:0
          predicates:
            - Path=/videos/**, 
        - id: notification
          uri: http://localhost:0
          predicates:
            - Path=/notifications/**, 
        - id: dashboard
          uri: http://localhost:0
          predicates:
            - Path=/fileUploadStatuses/**, 
        - id: frontend
          uri: http://localhost:8080
          predicates:
            - Path=/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true


---

spring:
  profiles: docker
  cloud:
    gateway:
      routes:
        - id: drive
          uri: http://drive:8080
          predicates:
            - Path=/files/**, 
        - id: indexer
          uri: http://indexer:8080
          predicates:
            - Path=/fileIndices/**, 
        - id: videoProcessing
          uri: http://videoProcessing:8080
          predicates:
            - Path=/videos/**, 
        - id: notification
          uri: http://notification:8080
          predicates:
            - Path=/notifications/**, 
        - id: dashboard
          uri: http://dashboard:8080
          predicates:
            - Path=/fileUploadStatuses/**, 
        - id: frontend
          uri: http://frontend:8080
          predicates:
            - Path=/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true

server:
  port: 8080
